server:
  port: 11000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.211.55.4:3306/wyzmall_wms?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true
    username: root
    password: Xxzs990416
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: wyzmall-ware

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml